name: Citibike Data Fetch

on:
  # 每小時觸發一次 (UTC 時間)。注意：GitHub Actions 的排程使用 UTC，
  # 但我們的程式碼內部會根據紐約時區來記錄時間，所以結果符合需求
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run data fetch script
        run: python src/script.py

      - name: List files for debugging
        run: ls -R

      # 若要保存產生的檔案，可使用 artifact 上傳功能
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CitibikeData
          path: data/
