name: Citibike Data Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run data fetch script
        run: python src/script.py

      - name: List files for debugging
        run: ls -R

      - name: Commit data files to data branch
        run: |
          # 設定 Git 使用者資訊
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # 取得遠端分支資訊
          git fetch origin
      
          # 在當前 HEAD 基礎上建立/切換到 data 分支（不依賴已存在的分支）
          git checkout -b data
      
          # 將 data 資料夾加入版本控制
          git add data/
      
          # 若有變更才 commit
          git diff --cached --exit-code || git commit -m "Update data files at $(date)"
      
          # 將本地 data 分支推送到遠端，並設定上游
          git push --set-upstream origin data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
